-- ============================================================
-- SEED: Códigos de demora para la aerolínea (airline_id = 3)
-- Si ya existe (airline_id, codigo) se actualiza la descripción.
-- ============================================================

SET NAMES utf8mb4;

INSERT INTO `codigo_demoras` (`codigo`, `descripcion`, `airline_id`) VALUES
('01', 'DEMORAS INTERNAS NACIONALES', 3),
('02', 'DEMORAS INTERNAS INTERNACIONALES', 3),
('03', 'INCONTROLABLES CLIENTES', 3),
('04', 'VUELOS BORRADOS', 3),
('05', 'SEGURIDAD INTERNA', 3),
('06', 'NO DISPONIBILIDAD DE PUERTA DE EMBARQUE O POSICIÓN DE PARQUEO DEBIDO A LA PROPIA ACTIVIDAD DE LA COMPAÑÍA', 3),
('09', 'TIEMPO DE TRANSITO POR ITINERARIO INFERIOR QUE EL MINIMO DECLARADO COMO NECESARIO PARA EL TIPO DE AVION', 3),
('11', 'CHEQUEO TARDIO, aceptación de pasajeros después de la hora límite', 3),
('12', 'CHEQUEO TARDIO, congestión en el área de mostradores', 3),
('13', 'ERROR DE CHEQUEO, de pasajeros o equipajes', 3),
('14', 'SOBREVENTA, errores en reservaciones', 3),
('15', 'ABORDAJE, discrepancias y compaginación, pasajeros chequeados faltantes', 3),
('16', 'PUBLICIDAD COMERCIAL / CONVENIENCIA DE PASAJEROS, VIP, faltantes de prensa, comidas o elementos personales a abordar', 3),
('17', 'ORDEN (SOLICITUD) DE CATERING, solicitud incorrecta o tardía al proveedor', 3),
('18', 'PROCESAMIENTO DE EQUIPAJE, clasificación, etc.', 3),
('19', 'ABORDAJE', 3),
('21', 'DOCUMENTACIÓN, errores, etc.', 3),
('22', 'POSICIONAMIENTO TARDIO', 3),
('23', 'ACEPTACIÓN TARDÍA', 3),
('24', 'EMBALAGE INADECUADO', 3),
('25', 'SOBREVENTA, error de reservación', 3),
('26', 'PREPARACIÓN TARDÍA EN EL ALMACÉN', 3),
('27', 'DOCUMENTACIÓN, EMBALAGE, etc.', 3),
('28', 'POSICIONAMIENTO TARDÍO', 3),
('29', 'ACEPTACIÓN TARDÍA', 3),
('31', 'DOCUMENTACIÓN DEL AVIÓN DEMORADA O INEXACTA, peso y balance, declaración general, manifiesto de pasajeros, etc.', 3),
('32', 'CARGUE / DESCARGUE, carga voluminosa, especial, carga en cabina, falta de personal de cargue', 3),
('33', 'EQUIPO DE CARGUE, falta o daño del mismo, por ejemplo cargador de conteiner o pallet, falta de personal de cargue', 3),
('34', 'EQUIPO DE SERVICIO, falta o daño el mismo, falta de personal, por ejemplo escaleras', 3),
('35', 'LIMPIEZA DEL AVION', 3),
('36', 'TANQUEO / DESTANQUEO, proveedor de combustible', 3),
('36.1', 'TANQUEO / DESTANQUEO, proveedor de combustible', 3),
('37', 'CATERING, entrega o embarque tardío', 3),
('38', 'ULD (Unit Load Device, Dispositivo Unitario de Carga), es decir, contenedores, pallets, etc.) Falta de o en condición inutilizable', 3),
('39', 'EQUIPO TÉCNICO, falta o daño del mismo, falta de personal, por ejemplo remolque (pay mover)', 3),
('41', 'DEFECTOS DEL AVION', 3),
('42', 'MANTENIMIENTO PROGRAMADO, entrega demorada', 3),
('43', 'MANTENIMIENTO NO PROGRAMADO, pruebas especiales y / o trabajos adicionales más allá del mantenimiento normal programado', 3),
('44', 'REPUESTOS Y EQUIPO DE MANTENIMIENTO, falta o daño de los mismos', 3),
('45', 'REPUESTOS AOG (Aircraft On Ground), a ser llevados a o desde otra estación', 3),
('46', 'CAMBIO DE AVION, por razones técnicas', 3),
('47', 'AVIÓN DE RESERVA, falta de avión programado como de reserva, por razones técnicas', 3),
('48', 'AJUSTES A LA CONFIGURACIÓN / VERSIÓN DE CABINA PROGRAMADA', 3),
('51', 'DAÑO DURANTE OPERACIONES DE VUELO, Impacto con aves, impacto de rayos, turbulencia, aterrizaje duro o con sobrepeso, colisión durante carreteo', 3),
('52', 'DAÑO DURANTE OPERACIONES DE TIERRA, (sin responsabilidad de la aerolínea)', 3),
('52.1', 'DAÑO DURANTE OPERACIONES DE TIERRA, (con responsabilidad de la aerolínea)', 3),
('55', 'CONTROL DE SALIDAS (DEPARTURE CONTROL)', 3),
('56', 'PREPARACIÓN DE CARGA / DOCUMENTACIÓN', 3),
('57', 'PLANES DE VUELO', 3),
('58', 'FALLAS EN OTROS SISTEMAS AUTOMATIZADOS', 3),
('61', 'PLAN DE VUELO, demora en su elaboración o cambio del mismo, documentación de vuelo', 3),
('61A', 'PLAN DE VUELO, demora en su elaboración o cambio del mismo, documentación de vuelo', 3),
('62', 'REQUERIMIENTOS OPERACIONALES, combustible, alteración del cargue', 3),
('63', 'ABORDAJE TARDÍO DE LA TRIPULACIÓN TÉCNICA O PROCEDIMIENTOS DE SALIDA DEMORADOS, diferentes a conexiones de tripulaciones o uso de tripulaciones de reserva (ya sean solo los pilotos o la tripulación completa)', 3),
('64', 'FALTANTE DE TRIPULACIÓN TÉCNICA, enfermedad, esperando reserva, limitación de tiempo de vuelo, hora de alimentación, visa, certificados de vacuna, etc.', 3),
('65', 'SOLICITUDES ESPECIALES DE LA TRIPULACIÓN TÉCNICA, por fuera de los requerimientos operacionales', 3),
('66', 'ABORDAJE TARDÍO DE LA TRIPULACIÓN DE CABINA O PROCEDIMIENTOS ESPECIALES DE SALIDA, diferentes a conexiones de tripulaciones o uso de tripulaciones de reserva', 3),
('66A', 'ABORDAJE TARDÍO DE LA TRIPULACIÓN DE CABINA O PROCEDIMIENTOS ESPECIALES DE SALIDA, diferentes a conexiones de tripulaciones o uso de tripulaciones de reserva', 3),
('67', 'FALTANTE DE TRIPULACIÓN DE CABINA, enfermedad, esperando reserva, limitaciones de tiempo de vuelo, hora de alimentación, alimentación, visa, certificados de vacunación, etc.', 3),
('68', 'ERROR DE LA TRIPULACIÓN DE CABINA O SOLICITUDES ESPECIALES, por fuera de los requerimientos operacionales', 3),
('69', 'SOLICITUD DEL CAPITÁN DE UNA INSPECCION DE SEGURIDAD, inspección no rutinaria o extraordinaria', 3),
('71', 'AEROPUERTO DE SALIDA', 3),
('72', 'AEROPUERTO DE DESTINO', 3),
('73', 'AEROPUERTO ALTERNO DE DESTINO O EN RUTA', 3),
('75', 'DESHIELO DEL AVIÓN, remoción de hielo y/o nieve, prevención de escarcha, excluyendo indisponibilidad de equipo para estas tareas', 3),
('76', 'REMOCIÓN DE NIEVE, HIELO, AGUA Y ARENA DE LAS PISTAS', 3),
('77', 'MANEJO DE RAMPA DIFICULTADO POR CONDICIONES METEOROLÓGICAS ADVERSAS', 3),
('81', 'ATFM (Air Traffic Flow Management) DEBIDO A LIMITACION DE CAPACIDAD DEL SISTEMA DE ATC EN RUTA O A ALTA DEMANDA, problemas comunes de demanda / capacidad', 3),
('82', 'ATFM DEBIDO A PERSONAL O EQUIPOS DE ATC EN RUTA, capacidad reducida por Movimiento Sindical o déficit de personal o falla de equipos, demanda extraordinaria causada por reducción de capacidad en áreas vecinas', 3),
('83', 'ATFM DEBIDO A RESTRICCIÓN EN AEROPUERTO DE DESTINO, aeropuerto y / o pista cerrados debido a obstrucción, Movimiento Sindical, déficit de personal, conmoción política, reducción de ruido, limitaciones nocturnas, vuelos especiales', 3),
('84', 'ATFM DEBIDO A CONDICIONES METEOROLÓGICAS EN EL AEROPUERTO DE DESTINO', 3),
('85', 'MEDIDAS DE SEGURIDAD MANDATORIAS', 3),
('86', 'INMIGRACIÓN, ADUANAS, SANIDAD', 3),
('87', 'INSTALACIONES AEROPORTUARIAS, posiciones de estacionamiento de aviones, congestión en rampa, iluminación, edificios, limitación de puertas de embarque, etc.', 3),
('88', 'RESTRICCIONES EN EL AEROPUERTO DE DESTINO, aeropuerto y / o pista cerrados debido a obstrucción, movimiento Sindical, déficit de personal, conmoción política, reducción de ruido, limitaciones nocturnas, vuelos especiales', 3),
('89', 'RESTRICCIONES EN EL AEROPUERTO DE ORIGEN CON O SIN RESTRICCIONES DE AFTM, incluyendo servicios de Control de Tráfico Aéreo, remolque, arranque de motores, aeropuerto y / o pista cerrados por obstrucción o razones meteorológicas', 3),
('89.1', 'RESTRICCIONES EN EL AEROPUERTO DE ORIGEN CON O SIN RESTRICCIONES DE AFTM, incluyendo servicios de Control de Tráfico Aéreo, remolque, arranque de motores, aeropuerto y / o pista cerrados por obstrucción o razones meteorológicas', 3),
('89.2', 'RESTRICCIONES EN EL AEROPUERTO DE ORIGEN CON O SIN RESTRICCIONES DE AFTM, incluyendo servicios de Control de Tráfico Aéreo, remolque, arranque de motores, aeropuerto y / o pista cerrados por obstrucción o razones meteorológicas', 3),
('89.3', 'RESTRICCIONES EN EL AEROPUERTO DE ORIGEN CON O SIN RESTRICCIONES DE AFTM, incluyendo servicios de Control de Tráfico Aéreo, remolque, arranque de motores, aeropuerto y / o pista cerrados por obstrucción o razones meteorológicas', 3),
('91', 'CONEXION DE CARGA O EQUIPAJE, esperando carga o equipaje de otro vuelo', 3),
('91.1', 'CONEXION DE CARGA O EQUIPAJE', 3),
('92', 'ERROR DE CHEQUEO CONTINUADO, de pasajeros y equipaje desde otros vuelos', 3),
('92.1', 'ERROR DE CHEQUEO CONTINUADO', 3),
('93', 'ROTACIÓN DE AERONAVES, llegada demorada de un avión de otro vuelo o de otro segmento de rutas previo', 3),
('94', 'ROTACIÓN DE TRIPULACIONES DE CABINA, esperando tripulantes de cabina que vienen en otro vuelo', 3),
('95', 'ROTACIÓN DE TRIPULACIÓN, esperando tripulación que viene en otro vuelo, pilotos o la tripulación completa', 3),
('96', 'CONTROL DE OPERACIONES, cambios de ruta, desviación a otro aeropuerto, consolidación de vuelos (unir vuelos), cambios de avión por razones no técnicas', 3),
('97', 'MOVIMIENTO SINDICAL DENTRO DE LA COMPAÑÍA', 3),
('98', 'MOVIMIENTO SINDICAL FUERA DE LA COMPAÑÍA', 3)
ON DUPLICATE KEY UPDATE `descripcion` = VALUES(`descripcion`);
