-- ============================================================
-- SEED: Códigos de demora para la aerolínea (airline_id = 1)
-- INSERT IGNORE: si ya existe (airline_id, codigo) NO se inserta
-- ni se modifica la fila existente.
-- ============================================================

SET NAMES utf8mb4;

INSERT IGNORE INTO `codigo_demoras` (`codigo`, `descripcion`, `airline_id`) VALUES
('00', 'Operaciones simultaneas de carga', 1),
('01', 'Recuperación de peso/carga por condiciones climáticas', 1),
('03', 'Taxeos y tiempo en aire', 1),
('03A', 'Taxeo en salida (Taxi Out)', 1),
('03B', 'Tiempo en aire (air time)', 1),
('03C', 'Taxeo de llegada (taxi in)', 1),
('03D', 'Falta de carga', 1),
('04', 'Operación tarde por servicios o acuerdos comerciales', 1),
('04A', 'Servicios no disponibles por operación tarde', 1),
('04B', 'Cambios en la rotación para cumplir acuerdos comerciales de carga', 1),
('05', 'Faltante de información de demoras/Gerente de estación', 1),
('06', 'Gestión de HUB control', 1),
('07', 'No se requiere codificación (Ops Carga)', 1),
('09', 'Tiempo itinerado en tierra menor que el MTT', 1),
('11', 'Chequeo tarde de pasajeros (después del cierre)', 1),
('12', 'Chequeo tarde de pasajeros por congestión en mostradores', 1),
('13', 'Error bajo responsabilidad de servicio al pasajero (Check-in)', 1),
('14', 'Sobreventa', 1),
('14A', 'Sobreventa operacional', 1),
('14B', 'Sobreventa comercial', 1),
('15', 'Abordaje', 1),
('15A', 'Abordaje lento (Aeropuertos)', 1),
('15B', 'Abordaje lento (Tripulantes de cabina)', 1),
('15C', 'Solicitud y retiro de equipaje', 1),
('15D', 'Cobros por equipaje adicional', 1),
('16', 'Comportamiento de pasajeros', 1),
('16A', 'Comportamiento de pasajeros dentro de la aeronave', 1),
('16B', 'Comportamiento de pasajeros fuera de la aeronave', 1),
('18', 'Manejo de equipaje', 1),
('18A', 'Mayor tiempo de búsqueda de equipaje', 1),
('18B', 'Selección y conexión de equipaje', 1),
('18C', 'Equipaje rezagado', 1),
('19', 'Asistencia a pasajeros con movilidad reducida', 1),
('19A', 'Demora por asistencia a pasajeros con movilidad reducida', 1),
('19B', 'Novedades del proveedor de sillas de rueda', 1),
('21', 'Errores en documentos de carga', 1),
('22', 'Entrega o posicionamiento tardío de carga', 1),
('23', 'Aceptación tardía de la carga', 1),
('24', 'Inconvenientes al Cargue y Descargue de Aeronave (Carga)', 1),
('25', 'Sobreventa de carga', 1),
('26', 'Preparación tardía de carga en almacén', 1),
('27', 'Sobreventa de correo', 1),
('28', 'Entrega o posicionamiento tardío del correo', 1),
('29', 'Aceptación tardía del correo', 1),
('31', 'Documentos del avión demorados o inadecuados', 1),
('32', 'Cargue/Descargue de la aeronave', 1),
('33', 'Equipo de cargado', 1),
('34', 'Equipo de servicio en tierra', 1),
('35', 'Limpieza de aeronave', 1),
('35A', 'Limpieza de aeronave – Proveedor rampa', 1),
('35B', 'Limpieza de aeronave – Otros proveedores', 1),
('36', 'Combustible', 1),
('36A', 'Combustible - Proveedor', 1),
('36B', 'Combustible – Despacho de aeronaves', 1),
('36C', 'Combustible – Técnico de mantenimiento', 1),
('36D', 'Combustible – Operaciones Terrestres', 1),
('37', 'Servicio a bordo', 1),
('37A', 'Servicio a Bordo – Catering', 1),
('37B', 'Servicio a Bordo – Proveedor de BOB', 1),
('37C', 'Servicio a Bordo – Operaciones Terrestres', 1),
('38', 'Dispositivo unitario de carga (ULD)', 1),
('39', 'Equipo técnico en tierra', 1),
('39A', 'Equipo técnico en tierra – falla de equipo', 1),
('39B', 'Equipo técnico en tierra – falta de equipo', 1),
('41', 'Defectos en aeronave', 1),
('41A', 'Defectos en aeronave', 1),
('41B', 'Defectos en aeronave, registro de diferidos MEL/NEF', 1),
('42', 'Mantenimiento programado', 1),
('42A', 'Mantenimiento programado - Procesos de planeación de trabajos', 1),
('42B', 'Mantenimiento programado - Procesos de mantenimiento en servicio mayor', 1),
('42C', 'Mantenimiento programado - Procesos de mantenimiento en servicio menor o línea', 1),
('43', 'Mantenimiento no programado', 1),
('43A', 'Mantenimiento no programado - Procesos de MCC y jefes de flota', 1),
('43B', 'Mantenimiento no programado – Procesos de mantenimiento línea', 1),
('43C', 'Mantenimiento no programado – Limitaciones por políticas de la organización', 1),
('44', 'Repuestos de equipo y de mantenimiento', 1),
('44A', 'Repuestos de equipo y de mantenimiento - Procesos de planeación de inventarios', 1),
('44B', 'Repuestos de equipo y de mantenimiento - Procesos de compras y/o reparaciones', 1),
('44C', 'Repuestos de equipo y de mantenimiento - Procesos de almacén y/o herramientas', 1),
('44D', 'Repuestos de equipo y de mantenimiento - Procesos de talleres locales', 1),
('44E', 'Repuestos de equipo y de mantenimiento - Procesos de comercio exterior', 1),
('46', 'Cambio de aeronaves por razones técnicas', 1),
('48', 'Ajustes a la configuración / versión de cabina programada', 1),
('48A', 'Ajustes a la configuración / versión de cabina programada - Procesos de ingeniería de mantenimiento', 1),
('48B', 'Ajustes a la configuración / versión de cabina programada - Procesos de control de calidad', 1),
('51', 'Daños a la aeronave durante el vuelo', 1),
('51A', 'Daños a la aeronave durante el vuelo por causas externas', 1),
('51C', 'Daños a la aeronave durante el vuelo - Pilotos', 1),
('51D', 'Daños a la aeronave durante el vuelo - Tripulantes de cabina', 1),
('52', 'Daños a la aeronave en tierra', 1),
('52A', 'Daños a la aeronave en tierra por causas externas', 1),
('52B', 'Daños a la aeronave en tierra - Aeropuertos', 1),
('52C', 'Daños a la aeronave en tierra - Operaciones Terrestres', 1),
('52D', 'Daños a la aeronave en tierra - Mantenimiento', 1),
('52E', 'Daños a la aeronave en tierra - Pilotos', 1),
('52F', 'Daños a la aeronave en tierra - Tripulantes de cabina', 1),
('52G', 'Daños a la aeronave en tierra - Catering', 1),
('55', 'Falla en los sistemas automatizados', 1),
('55A', 'Falla en los sistemas automatizados', 1),
('55B', 'Falla en los sistemas automatizados por errores del personal', 1),
('58', 'Fallas en Infraestructura y equipos', 1),
('58A', 'Fallas en infraestructura y equipos', 1),
('58B', 'Fallas en infraestructura y equipos por errores del personal', 1),
('61', 'Documentos de vuelo', 1),
('61A', 'Aspectos operacionales (programación de tripulaciones)', 1),
('61B', 'Documentos del vuelo (agente de operaciones)', 1),
('61C', 'Documentos del vuelo (despacho)', 1),
('62', 'Requerimientos operacionales', 1),
('62A', 'Requerimientos operacionales de pilotos', 1),
('62B', 'Requerimientos operacionales de tripulantes de cabina', 1),
('62C', 'Requerimientos Operacionales - Redistribución del cargado (equipaje y carga)', 1),
('62D', 'Requerimientos operacionales – Requerimientos de CPC', 1),
('62E', 'Requerimientos operacionales – APU previamente diferido', 1),
('62F', 'Requerimientos operacionales - Frenos calientes', 1),
('63', 'Abordaje tarde de pilotos', 1),
('63A', 'Abordaje tarde de pilotos', 1),
('63B', 'Abordaje tarde de pilotos debido a transporte', 1),
('64', 'Limitaciones de pilotos', 1),
('64A', 'Limitaciones de pilotos (Por regulación)', 1),
('64B', 'Limitaciones de pilotos (por entrenamientos certificados)', 1),
('65', 'Requerimientos no operaciones o demora en procedimientos (Pilotos)', 1),
('65A', 'Requerimientos no operacionales (Pilotos)', 1),
('65B', 'Requerimientos de alimentación (Pilotos)', 1),
('66', 'Abordaje tarde de tripulantes de cabina', 1),
('66A', 'Abordaje tarde de tripulantes de cabina', 1),
('66B', 'Abordaje tarde de tripulantes de cabina debido a transporte', 1),
('67', 'Limitaciones de tripulantes de cabina', 1),
('67A', 'Limitaciones de tripulantes de cabina (por regulación)', 1),
('67B', 'Limitaciones de tripulantes de cabina (por entrenamientos certificados)', 1),
('68', 'Requerimientos no operacionales o demora en procedimientos (Tripulantes de cabina)', 1),
('68A', 'Requerimientos no operacionales (tripulantes de cabina)', 1),
('68B', 'Requerimientos de alimentación (tripulantes de cabina)', 1),
('69', 'Chequeo especial de seguridad (Pilotos)', 1),
('71', 'Mal clima en estación origen', 1),
('72', 'Mal clima en estación destino', 1),
('73', 'Mal clima en ruta o alterno (sistemas)', 1),
('75', 'Descongelamiento de aeronave', 1),
('76', 'Limpieza de aeropuerto', 1),
('77', 'Servicios en tierra suspendidos', 1),
('83', 'ATFM - Restricción de aeropuerto destino (Con restricciones de FLOW)', 1),
('83A', 'ATFM - Restricción de aeropuerto destino', 1),
('83B', 'ATFM - Requerimientos de nuevo slot en destino', 1),
('84', 'ATFM - Restricción de aeropuerto destino por condiciones meteorológicas (Con restricciones de FLOW)', 1),
('84A', 'ATFM - Restricción de aeropuerto destino por condiciones meteorológicas', 1),
('84B', 'ATFM - Requerimientos de nuevo slot en destino por condiciones meteorológicas', 1),
('85', 'Seguridad mandatoria', 1),
('85A', 'Seguridad mandatoria - aeronaves y tripulaciones', 1),
('85B', 'Seguridad mandatoria - pasajeros y equipaje', 1),
('85C', 'Seguridad mandatorio – interna', 1),
('86', 'Migración, aduanas y salubridad', 1),
('87', 'Infraestructura aeroportuaria', 1),
('87A', 'Infraestructura, operador del aeropuerto', 1),
('87B', 'Infraestructura aeroportuaria, servicios con terceros', 1),
('88', 'Restricciones en el aeropuerto destino (Sin restricciones de FLOW)', 1),
('89', 'Restricciones en aeropuerto origen (Con o sin restricciones de FLOW)', 1),
('89A', 'Autorización movimiento en tierra', 1),
('89B', 'Restricciones en aeropuerto origen', 1),
('89C', 'Restricciones ATFM en origen', 1),
('89D', 'Restricciones ATFM por condiciones meteorológica en origen', 1),
('91', 'Conexiones', 1),
('91A', 'Conexión de pasajeros', 1),
('91B', 'Conexión de equipaje o carga', 1),
('92', 'Error en chequeo de tránsitos (atribuible a estación origen)', 1),
('93', 'Rotación de aeronaves', 1),
('93A', 'Llegada tarde de la aeronave', 1),
('93B', 'Rotación de aeronave menor que MTT', 1),
('94', 'Rotación de tripulantes de cabina', 1),
('95', 'Rotación de pilotos o Tripulación completa', 1),
('96', 'Control de operaciones', 1),
('96A', 'Control de operaciones (Decisiones SOC)', 1),
('96B', 'Control de operaciones (Crew tracking)', 1),
('97', 'Huelga en aerolínea', 1),
('98', 'Huelga en otras entidades', 1),
('99', 'Discrepancias', 1);
